### PR TITLE
adding clamav horizontal pod autoscaler

### PR DESCRIPTION
**Pull request by gowdab**
- adding HPA to autoscale based on CPU , memory and requests target utilisation.
- Adding back ingress controller as the deployment and nginx supports TCP.

dry run on the helm install will give
```
# Source: clamav/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: clamav
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clamav
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
```

### CODE REVIEW

**Comment by gowdab** [comment]
@desaintmartin please review

**Comment by desaintmartin** [comment]
Thanks again! Indeed removing the Ingress was probably a bad move.

**Comment by gowdab** [comment]
@desaintmartin , can you please publish this release to helm hub as well..thank you

**Comment by desaintmartin** [comment]
Helm Hub has been deprecated and has been replaced by https://artifacthub.io/packages/helm/wiremind/clamav !

**Comment by gowdab** [comment]
awesome ..thank you !

**Pull request merged**
