### PR TITLE
Add security features; Use named port in service

### PR DESCRIPTION
**Pull request by aeimer**
Relates to https://github.com/wiremind/wiremind-helm-charts/issues/148

### CODE REVIEW

**Comment by aeimer** [comment]
Currently failing with: 
image

@desaintmartin Do you have an idea which files we need to adapt?

**Comment by desaintmartin** [comment]
Actually, at the time, I think the "official" Docker image was not available on any hub, and thus the mailu docker image was used. Maybe, if the official one works as expected, we should use it as it seems well-built.

**Comment by aeimer** [comment]
@desaintmartin So I tried to use the official image (clamav/clamav) but seems to be way more complex than the mailu one. We should create a ticket for switching to the official image, for now I secured the exisiting setup.

**Comment by desaintmartin** [comment]
Thanks again!

**Pull request merged**
